/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hp_myfirstapp_MyActivity */

#ifndef _Included_com_example_hp_myfirstapp_MyActivity
#define _Included_com_example_hp_myfirstapp_MyActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
